### ISSUE TITLE
Support FastAPI `0.100.0` and Pydantic 2.0.

### ISSUE THREAD

**Issue by toph-allen** [rstudio/fastapitableau#37]
Pydantic 2.0 has led to internal changes in FastAPI that make it incompatible with FastAPI-Tableau.

```bash
$ python app.py
Traceback (most recent call last):
  File "/Users/mike/rstudio/connect/examples/fastapitableau-example/app.py", line 1, in <module>
    from fastapitableau import FastAPITableau
  File "/Users/mike/rstudio/connect/examples/fastapitableau-example/env/lib/python3.10/site-packages/fastapitableau/__init__.py", line 1, in <module>
    from fastapitableau.applications import FastAPITableau
  File "/Users/mike/rstudio/connect/examples/fastapitableau-example/env/lib/python3.10/site-packages/fastapitableau/applications.py", line 17, in <module>
    from fastapitableau.routing import TableauRoute
  File "/Users/mike/rstudio/connect/examples/fastapitableau-example/env/lib/python3.10/site-packages/fastapitableau/routing.py", line 7, in <module>
    from fastapi.openapi.utils import get_flat_models_from_routes
ImportError: cannot import name 'get_flat_models_from_routes' from 'fastapi.openapi.utils' (/Users/mike/rstudio/connect/examples/fastapitableau-example/env/lib/python3.10/site-packages/fastapi/openapi/utils.py)
```

**Comment by ChaitaC** [comment]
@toph-allen Is this ticket waiting in QA for any specific tests? or can we move it to verified column?
